// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ytdlp.Ui.Infrastructure.Persistence;

#nullable disable

namespace Ytdlp.Ui.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Ytdlp.Ui.Infrastructure.Persistence.Entities.AdminSessionRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IssuedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RevokedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("AdminSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sessions_Expiration", "\"ExpiresAt\" > \"IssuedAt\"");
                        });
                });

            modelBuilder.Entity("Ytdlp.Ui.Infrastructure.Persistence.Entities.DownloadArtifactRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DownloadId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReady")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkspaceGeneration")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadId", "WorkspaceGeneration", "RelativePath")
                        .IsUnique();

                    b.ToTable("DownloadArtifacts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Artifacts_Size", "\"Size\" IS NULL OR \"Size\" >= 0");
                        });
                });

            modelBuilder.Entity("Ytdlp.Ui.Infrastructure.Persistence.Entities.DownloadAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DownloadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InitialState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<long>("QueuedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadId")
                        .IsUnique()
                        .HasDatabaseName("IX_Attempts_OneActive")
                        .HasFilter("\"Status\" IN ('Pending', 'Running')");

                    b.HasIndex("DownloadId", "Number")
                        .IsUnique();

                    b.HasIndex("Status", "QueuedAt", "Id");

                    b.ToTable("DownloadAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Attempts_Number", "\"Number\" >= 1");
                        });
                });

            modelBuilder.Entity("Ytdlp.Ui.Infrastructure.Persistence.Entities.DownloadRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttemptStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CurrentAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailedState")
                        .HasColumnType("TEXT");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicationState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeState")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkspaceGeneration")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUrl")
                        .IsUnique();

                    b.ToTable("Downloads", null, t =>
                        {
                            t.HasCheckConstraint("CK_Downloads_Version", "\"Version\" >= 1");
                        });
                });

            modelBuilder.Entity("Ytdlp.Ui.Infrastructure.Persistence.Entities.StageExecutionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ArtifactId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DownloadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Progress")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("ReusedFromStageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId", "Stage")
                        .IsUnique();

                    b.HasIndex("DownloadId", "ArtifactId");

                    b.HasIndex("DownloadId", "AttemptId");

                    b.HasIndex("DownloadId", "ReusedFromStageId");

                    b.ToTable("StageExecutions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Stages_Progress", "\"Progress\" IS NULL OR (\"Progress\" >= 0 AND \"Progress\" <= 100)");
                        });
                });

            modelBuilder.Entity("Ytdlp.Ui.Infrastructure.Persistence.Entities.StorageTransferRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DownloadId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpectedSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MultipartUploadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObjectKey")
                        .IsUnique();

                    b.HasIndex("DownloadId", "ArtifactId");

                    b.HasIndex("DownloadId", "PublicationId")
                        .IsUnique();

                    b.ToTable("StorageTransfers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transfers_Size", "\"ExpectedSize\" >= 0");
                        });
                });

            modelBuilder.Entity("Ytdlp.Ui.Infrastructure.Persistence.Entities.DownloadArtifactRecord", b =>
                {
                    b.HasOne("Ytdlp.Ui.Infrastructure.Persistence.Entities.DownloadRecord", null)
                        .WithMany()
                        .HasForeignKey("DownloadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ytdlp.Ui.Infrastructure.Persistence.Entities.DownloadAttemptRecord", b =>
                {
                    b.HasOne("Ytdlp.Ui.Infrastructure.Persistence.Entities.DownloadRecord", null)
                        .WithMany()
                        .HasForeignKey("DownloadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ytdlp.Ui.Infrastructure.Persistence.Entities.StageExecutionRecord", b =>
                {
                    b.HasOne("Ytdlp.Ui.Infrastructure.Persistence.Entities.DownloadArtifactRecord", null)
                        .WithMany()
                        .HasForeignKey("DownloadId", "ArtifactId")
                        .HasPrincipalKey("DownloadId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ytdlp.Ui.Infrastructure.Persistence.Entities.DownloadAttemptRecord", null)
                        .WithMany()
                        .HasForeignKey("DownloadId", "AttemptId")
                        .HasPrincipalKey("DownloadId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ytdlp.Ui.Infrastructure.Persistence.Entities.StageExecutionRecord", null)
                        .WithMany()
                        .HasForeignKey("DownloadId", "ReusedFromStageId")
                        .HasPrincipalKey("DownloadId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Ytdlp.Ui.Infrastructure.Persistence.Entities.StorageTransferRecord", b =>
                {
                    b.HasOne("Ytdlp.Ui.Infrastructure.Persistence.Entities.DownloadArtifactRecord", null)
                        .WithMany()
                        .HasForeignKey("DownloadId", "ArtifactId")
                        .HasPrincipalKey("DownloadId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
